version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs-api
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - DB_HOST=database
  #     - DB_PORT=5432
  #     - DB_USER=postgres
  #     - DB_PASS=your_password
  #     - DB_NAME=ecommerce
  #     - JWT_SECRET=secret1
  #   depends_on:
  #     - database
  #   volumes:
  #     - .:/usr/src/app
  #   command: ['npm', 'run', 'start:prod']

  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ecommdb_paswrd1
      POSTGRES_DB: ecommercedb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '3800:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database
